[Optimize] optimize sdk release pipeline

diff --git a/.github/workflows/android-release.yml b/.github/workflows/android-release.yml
--- a/.github/workflows/android-release.yml
+++ b/.github/workflows/android-release.yml
@@ -4,14 +4,49 @@ on:
   push:
     tags:
       - '*'
+  workflow_dispatch:
+    inputs:
+      tag:
+        description: 'release tag'
+        required: false
+        type: string
+      publish_release:
+        description: 'whether to publish to github release'
+        required: false
+        type: boolean
+        default: true
 
 permissions:
   contents: write
 
 jobs:
+  get-version:
+    runs-on: lynx-ubuntu-22.04-medium
+    timeout-minutes: 60
+    outputs:
+      version: ${{ steps.get_version.outputs.VERSION }}
+    steps:
+      - name: Get Version
+        id: get_version
+        run: |-
+          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
+            version=${{ github.event.inputs.tag }}
+          else
+            version=$(echo ${{ github.ref }} | awk -F "/" '{print $3}')
+          fi
+          if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ || \
+                $version =~ ^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ || \
+                $version =~ ^[0-9]+\.[0-9]+\.[0-9]+-alpha\.[0-9]+$ ]]; then
+            echo "Version is valid"
+            echo "VERSION=$version" >> $GITHUB_OUTPUT;
+          else
+            echo "Version is invalid"
+            exit 1
+          fi
+
   android-release:
     runs-on: lynx-ubuntu-22.04-medium
-
+    needs: get-version
     steps:
     - name: Download Source
       uses: actions/checkout@v4.2.2
@@ -23,7 +58,7 @@ jobs:
 
     - name: Get Tag Information
       run: |-
-        version=$(echo ${{ github.ref }} | awk -F "/" '{print $3}')
+        version=${{ needs.get-version.outputs.version }}
         echo "VERSION=$version" >> $GITHUB_OUTPUT;
       id: get_tag
 
@@ -56,6 +91,7 @@ jobs:
       id: build_artifact
 
     - name: Push to release
+      if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.publish_release == true) }}
       uses: ncipollo/release-action@v1
       with:
         tag: ${{ steps.get_tag.outputs.VERSION }}
diff --git a/.github/workflows/publish-pod.yml b/.github/workflows/publish-pod.yml
--- a/.github/workflows/publish-pod.yml
+++ b/.github/workflows/publish-pod.yml
@@ -4,10 +4,41 @@ on:
   push:
     tags:
       - '*'
+  workflow_dispatch:
+    inputs:
+      tag:
+        description: 'release tag'
+        required: false
+        type: string
 
 jobs:
+  get-version:
+    runs-on: lynx-ubuntu-22.04-medium
+    timeout-minutes: 60
+    outputs:
+      version: ${{ steps.get_version.outputs.VERSION }}
+    steps:
+      - name: Get Version
+        id: get_version
+        run: |-
+          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
+            version=${{ github.event.inputs.tag }}
+          else
+            version=$(echo ${{ github.ref }} | awk -F "/" '{print $3}')
+          fi
+          if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ || \
+                $version =~ ^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ || \
+                $version =~ ^[0-9]+\.[0-9]+\.[0-9]+-alpha\.[0-9]+$ ]]; then
+            echo "Version is valid"
+            echo "VERSION=$version" >> $GITHUB_OUTPUT;
+          else
+            echo "Version is invalid"
+            exit 1
+          fi
+
   publish-pod:
     runs-on: macos-13
+    needs: get-version
     steps:
       - name: Download Source
         uses: actions/checkout@v4.2.2
@@ -16,7 +47,7 @@ jobs:
           SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk bundle install --path .bundle
       - name: Get Tag Information
         run: |-
-          version=$(echo ${{ github.ref }} | awk -F "/" '{print $3}')
+          version=${{ needs.get-version.outputs.version }}
           echo "VERSION=$version" >> $GITHUB_OUTPUT;
         id: get_tag
       - name: Publish to CocoaPods Repo
